CREATE TABLE userinfo (
    user_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    user_name VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    userDesc VARCHAR(255) NOT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8;